### ISSUE TITLE
Doesn't work (buildANewBotWithoutGettingTheToken method is broken)

### ISSUE THREAD

**Issue by Ezzaldean9** [WeeeeeeeeeeS/DiscordBotTokenCreator#1]
Bot not work , It does not create a team or build the bot , but create the bot

**Comment by WeeeeeeeeeeS** [comment]
Sorry for the late response. There's a bug in the 'buildANewBotWithoutGettingTheToken/resettoken' methods. I will try to fix it next weekend!

**Comment by WeeeeeeeeeeS** [comment]
Fixed
