### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by Ezzaldean9** [WeeeeeeeeeeS/DiscordBotTokenCreator#2]
![image](https://user-images.githubusercontent.com/65916848/222552175-aa6397f4-7f17-4dba-9309-83db9a64b5bd.png)
So far there is the same problem create the bot but didnt build the bot

**Comment by WeeeeeeeeeeS** [comment]
Use the new release.. v1.1

**Comment by WeeeeeeeeeeS** [comment]
Hello, I implemented a new fix, try it and tell me. (Better outputs)

https://github.com/WeeeeeeeeeeS/DiscordBotTokenCreator/releases/tag/untagged-8696523b53b15130ea49

**Comment by Ezzaldean9** [comment]
Request failed with response code Response{protocol=h2, code=400, message=, url=https://discord.com/api/applications/1081129599041294408/bot}
Response body: {"message": "Invalid two-factor code", "code": 60008}
The same problem has not been resolved

**Comment by WeeeeeeeeeeS** [comment]
Hello! The response says that the two-factor code is invalid. Please fix the JSON file and add a correct 2FA secret.

**How**?
https://letmegooglethat.com/?q=How+to+extract+secret+2fa+key+from+(YOUR+TOTP+APP)

**Or**, you can generate a new 2FA secret by going to Discord > Settings > My Account > Disable 2FA > Enable 2FA > Copy the secret > Add it to the JSON > Add it to your TOTP generator app > Run the program.
( https://www.androidpolice.com/how-to-set-up-two-factor-authentication-on-discord/#:~:text=Enable%202FA%20on%20Discord%20desktop%20and%20web&text=In%20the%20My%20Account%20tab,digit%20code%20to%20enable%202FA. )

This tool requires the following thing (STEP 5#)
![image](https://user-images.githubusercontent.com/47720055/222674086-854222ec-0cea-4bee-9103-644c6689cb02.png)

**Comment by Ezzaldean9** [comment]
I just generate a new secret and got the same issue

**Comment by WeeeeeeeeeeS** [comment]
did you activate it?

**Comment by Ezzaldean9** [comment]
yes

**Comment by Ezzaldean9** [comment]
create the team and bot but not build it

**Comment by WeeeeeeeeeeS** [comment]
creating a team doesn't require a 2Fa code

**Comment by Ezzaldean9** [comment]
> Do you use it like this?
> "secret": "xssz 4eey mztzf fbsq",

Yess

**Comment by WeeeeeeeeeeS** [comment]
Did you save the json file? 
If you give the tool wrong inputs, it will give you the wrong outputs, and it won't work.

**Comment by Ezzaldean9** [comment]
Yes i save the file

**Comment by WeeeeeeeeeeS** [comment]
It should work then. Try rerunning it. Discord allows you to use each secret key once..

**Comment by WeeeeeeeeeeS** [comment]
"The generated number, not the secret key"*

**Comment by Ezzaldean9** [comment]
The Bot and Team is created and the  bot is not build

**Comment by WeeeeeeeeeeS** [comment]
As i mentioned up.. creating a team or creating a new app doesn't require a 2fa code.. you can view the code, and you will understand how it works.
I am confident that the tool is working. I have been using it for the past 3 months, non-stop. "I created over 2k bots."

**Comment by Ezzaldean9** [comment]
What do I do now for the tool to work?

**Comment by WeeeeeeeeeeS** [comment]
Just fix the 2fa problem. Ask a friend to help you generate a new secret

**Comment by Ezzaldean9** [comment]
I generate the new secret and i add it to google authenticator and i add the secret to the config file

**Comment by Ezzaldean9** [comment]
![image](https://user-images.githubusercontent.com/65916848/222686153-accefc0f-467e-42d0-8450-4ee0825d2c14.png)

**Comment by WeeeeeeeeeeS** [comment]
Did u activate it (discord side)

**Comment by Ezzaldean9** [comment]
Yes i activate it

**Comment by WeeeeeeeeeeS** [comment]
Thats strange.. it should work

**Comment by Ezzaldean9** [comment]
Did I do everything right?

**Comment by WeeeeeeeeeeS** [comment]
As you said yes. As the request says no..
Try rerunning again.. if it didn't work.get a new secret and activiate it, then wait a min so a new number will be generated

**Comment by WeeeeeeeeeeS** [comment]
As you said yes. As the request says no..
Try rerunning again.. if it didn't work.get a new secret and activate it, then wait a min so a new number will be generated
