### ISSUE TITLE
App icon

### ISSUE THREAD

**Issue by Ezzaldean9** [WeeeeeeeeeeS/DiscordBotTokenCreator#4]
How can I add an avatar to the application
like the name
i can use ("avatar",avatar link") ?

**Comment by Ezzaldean9** [comment]
I do not know about it, but I have experience in modifying the codes only, so you can give me the addition and I will add it

**Comment by WeeeeeeeeeeS** [comment]
سلام, للاسف ما راح اقدر اضيف هذه الميزه ع البرنامج, لاني مشغول جداً بهذه الفتره..
المهم, اي مبرمج بيفهم بالjava بيقدر يضيفها لك.
